name: gemini_api_ex
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.2.2
  envied: ^0.5.3
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  flutter_markdown: ^0.6.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  envied_generator:
  riverpod_generator:
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

